### ISSUE TITLE
Ignore-list is cleared after each reload

### ISSUE THREAD

**Issue by gitgot-sucka** [HgAlexx/Buffet#80]
Classic 1.15.7.61528

When I type "/buffet ignore-add" and link [Festive Dumplings] I will receive a positive confirmation that festive dumplings have been added to my ignore list.  

I then check by typing "/buffet ignore-list" and it further confirms that [festive dumplings] are on my ignore list and I can also visually confirm because they have now disappeared from the macro that is on my bars.

After a reload, I notice that festive dumplings have been reinstated on my bars via the buffet macro even though they should still be on my ignore list.  Further, when I query "/buffet ignore-list" it says "Buffet: The ignore list is empty.

**Comment by HgAlexx** [comment]
Fixed in release 124.

Thanks for the report !

**Comment by gitgot-sucka** [comment]
Issue still persists :(

Disabled all addons and did a test run, unfortunately it's still treating the ignore-list as a session-ignore-list

[https://i.imgur.com/pRvsTCs.png](https://i.imgur.com/pRvsTCs.png)

**Comment by vb1508** [comment]
Issue still persists for me on 126 beta :-/

**Comment by HgAlexx** [comment]
Should be fixed in version 127.
For some reason, the code to load/save settings was working on retail but not on classic :(

**Comment by vb1508** [comment]
Fixed in 127, tyvm :-)
